### ISSUE TITLE
tasks.bootBuildImage 관련 문의

### ISSUE THREAD

**Issue by ondjj** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#8]
build.gradle.kts 파일 내부 최하단에 위치한 설정에 타입 불일치로 에러 문구가 발생합니다.

<img width="637" alt="스크린샷 2024-01-25 오후 3 59 39" src="https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/86146128/bc22f8d5-00df-4aa1-9a40-f5445d9c317b">

현재 docker를 통해 MySQL 컨테이너 러닝한 후 서버를 한 번 돌려보려고하는데 연관된 이슈인지 모르겠으나 
`SQLException`으로 접근 제한 로그가 찍히네요. 

<img width="1206" alt="스크린샷 2024-01-25 오후 4 00 48" src="https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/86146128/c0279e6b-c1c4-4ad0-b745-b707be4399b6">

Docker 컨테이너는 문제 없이 잘 작동하고 있습니다.

![스크린샷 2024-01-25 오후 4 02 10](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/86146128/edc8b6cd-d488-46d5-9c77-501d25601b4e)

혹시 추가 설정이 필요한데 제가 놓친 부분이 있는걸까요?

**Comment by CheorHyeon** [comment]
application.yml에 db연결정보를 혹시 바꾸셨을까요? 도커 컴포트 yml파일에 보시면 호스트 컴퓨터의 13306포트와 MySQL이 띄워질 컨테이너 3306포트와 연결하도록 되어있어서 localhost나 172.17.0.1로 둬야할 것 같습니다!
```
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/wanted
    driver-class-name: com.mysql.cj.jdbc.Driver
```
